### ISSUE TITLE
Sound effects required

### ISSUE THREAD

**Issue by bcvery1** [wayovertheregaming/catastrophy#11]
Files should have no spaces or special characters, ideally use camelCase

Files need to be stored in:
assets/audio/

They can be any of:

mp3
ogg (vorbis)
wav
flac

We need the following sound effects:
 - cat walking
 - birds chirping
 - cat drinking water
 - Cat urinating
 - cat pooping
 - door opening
 - door closing
 - whistling sound (as in something falling)
 - snoring
 - tv noise
 - children excitedly chattering

@PhantomRaviolis add comment for more - once this is started, create separate issues for additional required sounds

**Comment by bb2and8** [comment]
Done
