### ISSUE TITLE
Write riddles

### ISSUE THREAD

**Issue by bcvery1** [wayovertheregaming/catastrophy#19]
We need riddles for part of the challenges in the game.

They should be medium difficulty, ideally (but not necessarily and definitely not all) humorous.  We should have more than we strictly need; this way we can randomise what gets asked improving replayability.  Also, if a question is answered wrong, we can offer a different riddle, rather than letting them reguess

Create an CSV asset of the following structure:
```csv
question_text, correct_answer, incorrect_answer1, incorrect_answer2, incorrect_answer3
```

We'll deal with reading them into the application in another issue

**Comment by PhantomRaviolis** [comment]
I assume the incorrect answer is the phrase the player receives back if answer is incorrect?

**Comment by bcvery1** [comment]
No, correct and incorrect answers will be provided as a multiple choice list

**Comment by PhantomRaviolis** [comment]
Ahhhhhhhhhhhhhhhhh, that makes more sense.
