### ISSUE TITLE
Play sound prep

### ISSUE THREAD

**Issue by bcvery1** [wayovertheregaming/catastrophy#35]
For each file we need to add a reference to it in `cataudio/cataudio.go`

Line 32 is currently `allAudioFiles = map[string]*audio{}`

Add a reference to each file in this structure using the following pattern:
If you add a file called 'music1.mp3' (which should be repeated over and over) and a file called 'meow.mp3' (which should be played once), you can add them like this (still line 32):
```go
allAudioFiles = map[string]*audio{
  "music1.mp3": &audio{loops: -1},
  "meow.mp3": &audio{loops: 0},
}
```

Note that both lines have a comma at the end

**Comment by bb2and8** [comment]
Done
